services:
  app:
    build: .
    container_name: phaunabot
    restart: always
    ports:
      - "3002:3002"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    stdin_open: true
    tty: true
    command: npm start
